---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: agentgateway
  namespace: ai-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: agentgateway
