---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-cloudflare-r2"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-volsync-cloudflare-r2-secret"
    template:
      data:
        RESTIC_REPOSITORY: "s3:{{ .R2_K8S_ENDPOINT_URL }}/{{ .R2_K8S_RESTIC_REPOSITORY_PATH }}/${APP}"
        RESTIC_PASSWORD: "{{ .R2_K8S_RESTIC_REPOSITORY_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .R2_K8S_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .R2_K8S_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: cloudflare-r2
