---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:

  create-secret:
    desc: Create 1Password Connect secret for external-secrets
    dir: '{{.ROOT_DIR}}'
    cmds:
      - kubectl create namespace external-secrets --dry-run=client -o yaml | kubectl apply -f -
      - kubectl create secret generic onepassword-secret
        --from-file=1password-credentials.json={{.ROOT_DIR}}/credentials.json
        --namespace=external-secrets
        --dry-run=client -o yaml | kubectl apply -f -
