---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app media-pvc
  namespace: &namespace media
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/downloads/pvc/app
  components:
    - ../../../../components/shared-media
  prune: true
  retryInterval: 2m
  postBuild:
    substitute:
      NAMESPACE: *namespace
      # Optional overrides:
      # SHARED_MEDIA_CLAIM: "my-custom-pvc-name"
      # SHARED_MEDIA_CAPACITY: "10Ti"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
