---
# yaml-language-server: $schema=https://crd.movishell.pl/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
spec:
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --default_lua_flags=allow-undeclared-keys
    - --s3_endpoint=$(AWS_ENDPOINT_URL)
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: AWS_ACCESS_KEY_ID
          name: dragonfly-secret
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: AWS_SECRET_ACCESS_KEY
          name: dragonfly-secret
    - name: AWS_ENDPOINT_URL
      valueFrom:
        secretKeyRef:
          name: dragonfly-secret
          key: AWS_ENDPOINT_URL
  image: ghcr.io/dragonflydb/dragonfly:v1.29.0
  labels:
    dragonflydb.io/cluster: dragonfly
  replicas: 3
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 512Mi
  snapshot:
    dir: "s3://home-ops-dragonfly"
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: "DoNotSchedule"
      labelSelector:
        matchLabels:
          app.kubernetes.io/part-of: dragonfly
