---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-downloads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ceph-filesystem
