---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app changedetection
  namespace: &namespace self-hosted
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/selfhosted/changedetection/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: security
    - name: volsync
      namespace: system
  components:
    - ../../../../components/volsync
    - ../../../../components/gatus/guarded
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      APP_UID: "2000"
      APP_GID: "2000"
      VOLSYNC_CLAIM: changedetection-config
      VOLSYNC_CAPACITY: 1Gi
  prune: true
  wait: false
  interval: 30m
  timeout: 5m
