---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app excalidraw
  namespace: &ns selfhosted
spec:
  targetNamespace: *ns
  components:
    - ../../../../components/gatus/guarded
  path: ./kubernetes/apps/selfhosted/excalidraw/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 90m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      HOSTNAME: draw.${SECRET_DOMAIN}
