---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nats
  namespace: database
spec:
  jobLabel: app.kubernetes.io/instance
  namespaceSelector:
    matchNames:
      - database
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
      app.kubernetes.io/instance: nats
      app.kubernetes.io/component: nats
  podMetricsEndpoints:
    - port: prom-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
