---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-secret
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: Proton VPN
        property: WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: Proton VPN
        property: WIREGUARD_PRESHARED_KEY
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: Proton VPN
        property: WIREGUARD_ADDRESSES
    - secretKey: WIREGUARD_DNS
      remoteRef:
        key: Proton VPN
        property: WIREGUARD_DNS

    - secretKey: PUBLICIP_API_TOKEN
      remoteRef:
        key: Proton VPN
        property: IP2LOCATION_API_KEY

    - secretKey: xseed_api_key
      remoteRef:
        key: cross-seed
        property: api_key
    - secretKey: GLUETUN_CONTROL_SERVER_API_KEY
      remoteRef:
        key: gluetun
        property: api_key
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-gluetun
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-gluetun-secret
    creationPolicy: Owner
    template:
      data:
        auth.toml: |
          [[roles]]
          name = "gluetun-qb-port-sync"
          routes = [
            "GET /v1/publicip/ip",
            "GET /v1/openvpn/portforwarded"
          ]
          auth = "apikey"
          apikey = "{{ .gluetun_api_key }}"
  dataFrom:
    - extract:
        key: gluetun
      rewrite:
        - regexp:
            source: "(.*)"
            target: "gluetun_$1"
