---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-secret
    creationPolicy: Owner
  data:
    - secretKey: OPENVPN_USER
      remoteRef:
        key: nordvpn
        property: SERVICE_USERNAME
    - secretKey: OPENVPN_PASSWORD
      remoteRef:
        key: nordvpn
        property: SERVICE_PASSWORD
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: nordvpn
        property: WIREGUARD_PRIVATE_KEY
    # - secretKey: WIREGUARD_PRESHARED_KEY
    #   remoteRef:
    #     key: nordvpn
    #     property: WIREGUARD_PRESHARED_KEY
    # - secretKey: WIREGUARD_ADDRESSES
    #   remoteRef:
    #     key: nordvpn
    #     property: WIREGUARD_ADDRESSES
    # - secretKey: WIREGUARD_DNS
    #   remoteRef:
    #     key: nordvpn
    #     property: WIREGUARD_DNS

    - secretKey: PUBLICIP_API_TOKEN
      remoteRef:
        key: ip2location.io
        property: IP2LOCATION_API_KEY

    - secretKey: XSEED_APIKEY
      remoteRef:
        key: cross-seed
        property: CROSS_SEED_API_KEY
    - secretKey: GLUETUN_CONTROL_SERVER_API_KEY
      remoteRef:
        key: gluetun
        property: GLUETUN_API_KEY
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-gluetun
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qbittorrent-gluetun-secret
    creationPolicy: Owner
    template:
      data:
        auth.toml: |
          [[roles]]
          name = "gluetun-qb-port-sync"
          routes = [
            "GET /v1/publicip/ip",
            "GET /v1/openvpn/portforwarded"
          ]
          auth = "apikey"
          apikey = "{{ .GLUETUN_API_KEY }}"
  dataFrom:
    - extract:
        key: gluetun
