---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      qbittorrent:
        type: statefulset

        annotations:
          secret.reloader.stakater.com/reload: qbittorrent-secret,qbittorrent-gluetun-secret

        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65542 # gladius:external-services

        initContainers:
          # Remove CoreDNS - let Gluetun handle DNS internally
          # coredns:
          #   image:
          #     repository: mirror.gcr.io/coredns/coredns
          #     tag: 1.12.1
          #   args:
          #     - -conf
          #     - /etc/coredns/Corefile
          #   restartPolicy: Always

          gluetun:
            # Remove dependency on CoreDNS
            # dependsOn:
            #   - coredns
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            env:
              DOT: "on"
              # Use single DNS server for NordVPN
              DNS_ADDRESS: "103.86.96.100"
              HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH: &gluetunAuthPath /gluetun/auth.toml
              VPN_SERVICE_PROVIDER: nordvpn
              VPN_TYPE: wireguard
              VPN_INTERFACE: wg0
              WIREGUARD_MTU: 1280
              SERVER_COUNTRIES: "United States"
              # Try specific servers instead of cities
              SERVER_CITIES: "New York,Chicago,Los Angeles,Miami"
              VPN_PORT_FORWARDING: "off"
              FIREWALL_INPUT_PORTS: 8080
              FIREWALL_OUTBOUND_SUBNETS: 10.96.0.0/12,10.244.0.0/16,10.42.0.0/16 # Allow access to k8s subnets and pod network
              FIREWALL_VPN_INPUT_PORTS: 8080
              # Let Gluetun handle DNS internally - remove custom DNS setup
              # FIREWALL_VPN_OUTBOUND_PORTS: 53,853
              # FIREWALL_OUTBOUND_SUBNETS_ONLY: "off"
              # Use Gluetun's internal DNS instead of custom CoreDNS
              DNS_KEEP_NAMESERVER: "off"
              DNS_UPDATE_DELAY: "5s"
              FIREWALL: "off"
              HEALTH_VPN_DURATION_INITIAL: "300s" # Increase to prevent frequent restarts
              HEALTH_VPN_DURATION_ADDITION: "60s"
              PUBLICIP_API: ip2location
              HEALTH_TARGET_ADDRESS: "1.1.1.1:443" # Use IP instead of domain
              UPDATER_PERIOD: "24h"
              # Ensure all traffic goes through VPN
              BLOCK_MALICIOUS: "on"
              BLOCK_ADS: "off"
              BLOCK_SURVEILLANCE: "off"
            envFrom: &envFrom
              - secretRef:
                  name: qbittorrent-secret
            # resources:
            #   limits:
            #     squat.ai/tun: "1"
            restartPolicy: Always
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false

        containers:
          app:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.2
            env:
              UMASK: "022"
              QBT_WEBUI_PORT: &port 8080
              XSEED_HOST: cross-seed.downloads.svc.cluster.local
              XSEED_PORT: 2468
            envFrom: *envFrom
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - "pgrep qbittorrent-nox > /dev/null"
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - "pgrep qbittorrent-nox > /dev/null && netstat -tln | grep ':8080 ' > /dev/null"
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - "pgrep qbittorrent-nox > /dev/null"
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 60
            resources:
              requests:
                cpu: 150m
                memory: 2048Mi
              limits:
                memory: 8192Mi
            securityContext:
              runAsUser: 2000
              runAsGroup: 2000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          port-forward:
            image:
              repository: ghcr.io/bjw-s-labs/gluetun-qb-port-sync
              tag: 0.0.4@sha256:838ba41b3c736b23ae30f7e79a2610173f389a5ac6fb2b3e9c7bd482b9353c18
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *port
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            envFrom: *envFrom
            securityContext:
              runAsUser: 2000
              runAsGroup: 2000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      empty-config:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            port-forward:
              - path: /config
      downloads:
        type: nfs
        server: nas.${SECRET_DOMAIN}
        path: /mnt/storage/Media
        globalMounts:
          - path: /data/nas-media/Downloads/qbittorrent
            subPath: Downloads/qbittorrent
      gluetun-auth:
        type: secret
        name: qbittorrent-gluetun-secret
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: *gluetunAuthPath
                subPath: auth.toml
      coredns:
        type: configMap
        name: qbittorrent-coredns
        advancedMounts:
          qbittorrent:
            coredns:
              - path: /etc/coredns/Corefile
                subPath: Corefile
                readOnly: true
      scripts:
        type: configMap
        name: qbittorrent-scripts
        defaultMode: 0775
        advancedMounts:
          qbittorrent:
            app:
              - path: /config/scripts

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: *app
          gethomepage.dev/icon: https://raw.githubusercontent.com/loganmarchione/homelab-svg-assets/refs/heads/main/assets/qbittorrent.svg
          # gethomepage.dev/siteMonitor: coder.${SECRET_DOMAIN}
          gethomepage.dev/description: "qBittorrent is a free and open-source BitTorrent client."
          gethomepage.dev/pod-selector: app.kubernetes.io/name=prowlarr
        hostnames:
          - qbittorrent.${SECRET_DOMAIN}
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
