---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./storageclass.yaml
  - ./claims.yaml
  - ./setup-folders-job.yaml
  - ./subvolumegroup.yaml
