---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: autobrr-secret
    creationPolicy: Owner
    template:
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: &dbName "{{ .POSTGRES_DB_NAME }}"
        INIT_POSTGRES_HOST: &dbHost "{{ .POSTGRES_DB_HOST }}"
        INIT_POSTGRES_USER: &dbUser "{{ .POSTGRES_DB_USER_NAME }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .POSTGRES_DB_USER_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        AUTOBRR__DATABASE_TYPE: postgres
        AUTOBRR__POSTGRES_PORT: "5432"
        AUTOBRR__POSTGRES_DATABASE: *dbName
        AUTOBRR__POSTGRES_HOST: *dbHost
        AUTOBRR__POSTGRES_USER: *dbUser
        AUTOBRR__POSTGRES_PASS: *dbPass

        AUTOBRR__SESSION_SECRET: "{{ .AUTOBRR_SESSION_SECRET }}"

  dataFrom:
    - extract:
        key: autobrr
    - extract:
        key: cloudnative-pg
