---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: action-runner-controller
spec:
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
  selector:
    matchLabels:
      app.kubernetes.io/part-of: gha-rs-controller
  namespaceSelector:
    matchNames:
      - actions-runner-system
