---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: action-runner-controller
spec:
  podMetricsEndpoints:
    - interval: 15s
      path: /metrics
      targetPort: 8080
  selector:
    matchLabels:
      app.kubernetes.io/name: actions-runner-controller
  namespaceSelector:
    matchNames:
      - actions-runner-system
