extends:
  - "@commitlint/config-conventional"

rules:
  type-enum:
    - 2
    - always
    - [feat, update, fix, perf, refactor, style, test, revert]

  scope-enum:
    - 2
    - always
    - [build, ci, docs, src, test, misc]

  subject-case:
    - 2
    - always
    - ["lower-case", "sentence-case"]

  body-empty:
    - 2
    - always

  footer-empty:
    - 2
    - always
