---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

set: [pipefail]
shopt: [globstar]

vars:
  BOOTSTRAP_DIR: '{{.ROOT_DIR}}/bootstrap'
  KUBERNETES_DIR: '{{.ROOT_DIR}}/kubernetes'
  SCRIPTS_DIR: '{{.ROOT_DIR}}/scripts'
  TALOS_DIR: '{{.ROOT_DIR}}/talos'
  PRIVATE_DIR: '{{.ROOT_DIR}}/.private'
  TALOSCONFIG: '{{.ROOT_DIR}}/talos/clusterconfig/talosconfig'

env:
  KUBECONFIG: '{{.ROOT_DIR}}/kubeconfig'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.TALOSCONFIG}}'

includes:
  bootstrap: .taskfiles/bootstrap
  talos: .taskfiles/talos
  1password: .taskfiles/1password
  k8s: .taskfiles/k8s
  flux: .taskfiles/flux
  rook: .taskfiles/rook
  network: .taskfiles/network
  actions-runner: .taskfiles/actions-runner

tasks:

  default: task --list

  setup-dev-env:
    cmds:
      - mise install
      - pre-commit install --hook-type pre-commit --hook-type commit-msg
    desc: Setup dev environment and install pre-commit hooks

  reconcile:
    desc: Force Flux to pull in changes from your Git repository
    cmd: flux --namespace flux-system reconcile kustomization flux-system --with-source
    preconditions:
      - test -f {{.KUBECONFIG}}
      - which flux

  cleanup-failed-pods:
    desc: Remove all failed/error pods (keeps completed pods)
    cmd: kubectl delete pods --all-namespaces --field-selector=status.phase=Failed

  cleanup-succeeded-pods:
    desc: Remove old succeeded pods (keeps recent ones from last 24h)
    cmd: CUTOFF=$(date -d '1 day ago' -u +"%Y-%m-%dT%H:%M:%SZ") && kubectl get pods --all-namespaces --field-selector=status.phase=Succeeded -o json | jq -r --arg cutoff "$CUTOFF" '.items[] | select(.metadata.creationTimestamp < $cutoff) | [.metadata.namespace, .metadata.name] | @tsv' | while IFS=$'\t' read -r ns name; do kubectl delete pod "$name" -n "$ns"; done

  cleanup-error-pods:
    desc: Remove all pods in Error state
    cmd: kubectl get pods --all-namespaces --field-selector=status.phase!=Running,status.phase!=Succeeded,status.phase!=Pending --no-headers -o custom-columns="NAMESPACE:.metadata.namespace,NAME:.metadata.name" | while read -r ns name; do kubectl delete pod "$name" -n "$ns"; done

  cleanup-replicasets:
    desc: Remove old ReplicaSets with 0 desired replicas (excludes intentionally scaled ones)
    cmd: CUTOFF=$(date -d '1 day ago' -u +"%Y-%m-%dT%H:%M:%SZ") && kubectl get rs --all-namespaces -o json | jq -r --arg cutoff "$CUTOFF" '.items[] | select((.spec.replicas // 0) == 0 and (.status.replicas // 0) == 0 and .metadata.creationTimestamp < $cutoff) | [.metadata.namespace, .metadata.name] | @tsv' | while IFS=$'\t' read -r ns name; do kubectl delete rs "$name" -n "$ns"; done

  cleanup-all:
    desc: Clean up all failed pods, error pods, and unused replicasets
    cmds:
      - task: cleanup-failed-pods
      - task: cleanup-succeeded-pods
      - task: cleanup-error-pods
      - task: cleanup-replicasets
