---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: sklab-dev-tls
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: "sklab-dev-production-tls"
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &crt tls.crt
        remoteRef:
          remoteKey: sklab-dev-tls
          property: *crt
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: sklab-dev-tls
          property: *key
