apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: crunchy-postgres-user
  namespace: rook-ceph
spec:
  store: ceph-objectstore
  displayName: "Crunchy Postgres S3 User"
---
apiVersion: ceph.rook.io/v1
kind: CephBucketProvisioner
metadata:
  name: crunchy-postgres-bucket
  namespace: rook-ceph
spec:
  objectStoreName: ceph-objectstore
  bucketName: crunchy-postgres
