---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-aviator-coding-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: arc-aviator-coding-secret
    template:
      engineVersion: v2
      data:
        ACR_AVIATOR_CODING_APP_ID: "{{ .ACR_AVIATOR_CODING_APP_ID }}"
        ACR_AVIATOR_CODING_INSTALLATION_ID: "{{ .ACR_AVIATOR_CODING_INSTALLATION_ID }}"
        ACR_AVIATOR_CODING_WEBHOOK_SECRET_TOKEN: "{{ .ACR_AVIATOR_CODING_WEBHOOK_SECRET_TOKEN }}"
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: github
  data:
    - secretKey: ACR_AVIATOR_CODING_PRIVATE_KEY
      remoteRef:
        key: github-acr-all-repositories
        property: "private key"
