---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./tcp-route.yaml
configMapGenerator:
  - name: vector-aggregator-configmap
    files:
      - vector.yaml=./resources/vector.yaml
generatorOptions:
  disableNameSuffixHash: true
