---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aviator-coding-runner-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: aviator-coding-runner-secret
    template:
      engineVersion: v2
      data:
        github_app_id: "{{ .ACR_AVIATOR_CODING_APP_ID }}"
        github_app_installation_id: "{{ .ACR_AVIATOR_CODING_INSTALLATION_ID }}"
        github_app_private_key: "{{ .ACR_AVIATOR_CODING_PRIVATE_KEY }}"
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: github
  data:
    - secretKey: ACR_AVIATOR_CODING_PRIVATE_KEY
      remoteRef:
        key: github-acr-all-repositories
        property: "private key"
