---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openclaw-secret
    template:
      data:
        OPENCLAW_GATEWAY_PASSWORD: "{{ .OPENCLAW_GATEWAY_PASSWORD }}"
        OPENCLAW_GATEWAY_TOKEN: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
        ANTHROPIC_API_KEY_MAX: "{{ .ANTHROPIC_API_KEY_MAX }}"
        TELEGRAM_BOT_TOKEN: "{{ .OPENCLAW_TOKEN }}"
  dataFrom:
    - extract:
        key: openclaw
    - extract:
        key: ai-keys
    - extract:
        key: telegram
