---
# One-time job to create the complete home-ops directory structure
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-homeops-structure
  annotations:
    k8tz.io/inject: "false"
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300 # Clean up job after 5 minutes
  template:
    spec:
      containers:
        - name: setup
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Starting home-ops directory structure setup..."
              echo "Current working directory: $(pwd)"
              echo "Available disk space:"
              df -h /storage

              echo "Creating complete directory structure..."

              # Development directories
              mkdir -p /storage/Development/Projects
              mkdir -p /storage/Development/Tools
              mkdir -p /storage/Development/Learning
              mkdir -p /storage/Development/Repositories

              # Documents directories
              mkdir -p /storage/Documents/Personal/Finance
              mkdir -p /storage/Documents/Personal/Legal
              mkdir -p /storage/Documents/Personal/Medical
              mkdir -p /storage/Documents/Personal/Insurance
              mkdir -p /storage/Documents/Personal/Receipts
              mkdir -p /storage/Documents/Work/Projects
              mkdir -p /storage/Documents/Work/Contracts
              mkdir -p /storage/Documents/Work/Reports
              mkdir -p /storage/Documents/Work/Presentations
              mkdir -p /storage/Documents/Education/Certifications
              mkdir -p /storage/Documents/Education/Courses
              mkdir -p /storage/Documents/Education/Research
              mkdir -p /storage/Documents/Templates/Forms
              mkdir -p /storage/Documents/Templates/Contracts
              mkdir -p /storage/Documents/Templates/Documents

              # Media directories
              mkdir -p /storage/Media/Movies/Action
              mkdir -p /storage/Media/Movies/Comedy
              mkdir -p /storage/Media/Movies/Drama
              mkdir -p /storage/Media/Movies/Documentary
              mkdir -p /storage/Media/Movies/Horror
              mkdir -p /storage/Media/Movies/SciFi
              mkdir -p /storage/Media/Movies/Classics
              mkdir -p /storage/Media/TV/Series
              mkdir -p /storage/Media/TV/Documentaries
              mkdir -p /storage/Media/TV/News
              mkdir -p /storage/Media/TV/Kids
              mkdir -p /storage/Media/Music/Albums
              mkdir -p /storage/Media/Music/Singles
              mkdir -p /storage/Media/Music/Playlists
              mkdir -p /storage/Media/Music/Podcasts
              mkdir -p /storage/Media/Music/Audiobooks
              mkdir -p /storage/Media/Books/Fiction
              mkdir -p /storage/Media/Books/Non-Fiction
              mkdir -p /storage/Media/Books/Technical
              mkdir -p /storage/Media/Books/Comics
              mkdir -p /storage/Media/Books/Magazines
              mkdir -p /storage/Media/Photos/Family
              mkdir -p /storage/Media/Photos/Events
              mkdir -p /storage/Media/Photos/Travel
              mkdir -p /storage/Media/Photos/Screenshots
              mkdir -p /storage/Media/Games/ROMs
              mkdir -p /storage/Media/Games/ISOs
              mkdir -p /storage/Media/Games/Saves

              # Downloads directories
              mkdir -p /storage/Downloads/Browser
              mkdir -p /storage/Downloads/Torrents/Incomplete
              mkdir -p /storage/Downloads/Torrents/Complete
              mkdir -p /storage/Downloads/Torrents/Seeding
              mkdir -p /storage/Downloads/Software
              mkdir -p /storage/Downloads/Temp
              mkdir -p /storage/Downloads/Processing

              # Shared directories
              mkdir -p /storage/Shared/Family/Photos
              mkdir -p /storage/Shared/Family/Documents
              mkdir -p /storage/Shared/Family/Calendars
              mkdir -p /storage/Shared/Team/Projects
              mkdir -p /storage/Shared/Team/Resources
              mkdir -p /storage/Shared/Team/Handover
              mkdir -p /storage/Shared/Public/Templates
              mkdir -p /storage/Shared/Public/Tools
              mkdir -p /storage/Shared/Public/References

              # Resources directories
              mkdir -p /storage/Resources/Documentation/Manuals
              mkdir -p /storage/Resources/Documentation/Guides
              mkdir -p /storage/Resources/Documentation/References
              mkdir -p /storage/Resources/Assets/Images
              mkdir -p /storage/Resources/Assets/Icons
              mkdir -p /storage/Resources/Assets/Fonts
              mkdir -p /storage/Resources/Assets/Templates
              mkdir -p /storage/Resources/Datasets/Raw
              mkdir -p /storage/Resources/Datasets/Processed
              mkdir -p /storage/Resources/Datasets/Samples
              mkdir -p /storage/Resources/Libraries/Code
              mkdir -p /storage/Resources/Libraries/Scripts
              mkdir -p /storage/Resources/Libraries/Modules

              # System directories
              mkdir -p /storage/System/Configs/Kubernetes
              mkdir -p /storage/System/Configs/Applications
              mkdir -p /storage/System/Configs/Scripts
              mkdir -p /storage/System/Monitoring/Logs
              mkdir -p /storage/System/Monitoring/Metrics
              mkdir -p /storage/System/Monitoring/Reports
              mkdir -p /storage/System/Secrets/Certificates
              mkdir -p /storage/System/Secrets/Keys
              mkdir -p /storage/System/Secrets/Tokens
              mkdir -p /storage/System/Maintenance/Backups
              mkdir -p /storage/System/Maintenance/Updates
              mkdir -p /storage/System/Maintenance/Patches

              # Archives directories (for future cold storage)
              mkdir -p /storage/Archives/Yearly/2023
              mkdir -p /storage/Archives/Yearly/2024
              mkdir -p /storage/Archives/Yearly/2025
              mkdir -p /storage/Archives/Backups/System
              mkdir -p /storage/Archives/Backups/Applications
              mkdir -p /storage/Archives/Backups/Personal
              mkdir -p /storage/Archives/Old-Projects
              mkdir -p /storage/Archives/Legacy

              # Set proper permissions
              chmod -R 755 /storage

              echo "Directory structure created successfully!"
              echo "Complete directory tree:"
              find /storage -type d | sort

              echo "Verifying write permissions..."
              touch /storage/test-write && rm /storage/test-write && echo "Write test: SUCCESS" || echo "Write test: FAILED"

              echo "Final summary:"
              echo "Total directories created: $(find /storage -type d | wc -l)"
              echo "Storage usage after setup:"
              du -sh /storage

              echo "Home-ops directory structure setup complete!"
          volumeMounts:
            - name: homeops-storage
              mountPath: /storage
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      volumes:
        - name: homeops-storage
          persistentVolumeClaim:
            claimName: homeops-storage
      restartPolicy: OnFailure
