---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.jsonapiVersion: helm.toolkit.fluxcd.io/v2
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kagent
  install:
    timeout: 10m
    replace: true
    crds: CreateReplace
    createNamespace: true
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  driftDetection:
    mode: enabled
  maxHistory: 3
  values:
    providers:
      default: openAI # Use openAI as the provider name

      openAI:
        provider: OpenAI
        model: "xAI: Grok 4 Fast" # Your LiteLLM model
        apiKeySecretRef: litellm-provider-secret # Your existing secret
        apiKeySecretKey: LITELLM_API_KEY
        config:
          baseUrl: "http://litellm.ai.svc.cluster.local:4000/v1" # Point to LiteLLM
