---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname sabnzbd
  namespace: &namespace downloads
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/downloads/sabnzbd/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: downloads-pvc
      namespace: downloads
    - name: onepassword-store
      namespace: security
    - name: volsync
      namespace: system
  components:
    - ../../../../components/volsync
    - ../../../../components/shared-media
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: sabnzbd-config
      NAMESPACE: *namespace
      # Optional overrides:
      # SHARED_MEDIA_CLAIM: "my-custom-pvc-name"
      # SHARED_MEDIA_CAPACITY: "10Ti"
