---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: authentik-auth
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: HTTPROUTE_NAME_PLACEHOLDER
  extAuth:
    http:
      backendRefs:
        - name: authentik-server
          namespace: security
          port: 80
      path: /outpost.goauthentik.io/auth
      headersToBackend:
        - authorization
        - x-authentik-username
        - x-authentik-email
        - x-authentik-name
        - x-authentik-uid
