---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-nas-nfs"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-volsync-nas-nfs-secret"
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .K8S_RESTIC_REPOSITORY_PATH }}/home-ops-${APP}"
        RESTIC_PASSWORD: "{{ .K8S_RESTIC_REPOSITORY_PASSWORD }}"
  dataFrom:
    - extract:
        key: nas
