---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpoller
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: unpoller-secret
    template:
      engineVersion: v2
      data:
        UP_UNIFI_DEFAULT_URL: "{{ .UNIFI_API_URL }}"
        UP_UNIFI_DEFAULT_API_KEY: "{{ .UNIFI_API_KEY }}"
  dataFrom:
  - extract:
      key: unifi
