---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./local
  - ./remote-nas-minio
  - ./remote-nas-nfs
  - ./remote-cloudflare-r2
  - ./pvc.yaml
