---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./minio/externalsecret-minio.yaml
  - ./r2/externalsecret-r2.yaml
  - ./minio/replicationsource-minio.yaml
  - ./r2/replicationsource-r2.yaml
  - ./replicationdestination.yaml
  - ./pvc.yaml
