---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app litellm
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    controllers:
      litellm:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
            envFrom:
              - secretRef:
                  name: litellm-secret
        containers:
          app:
            image:
              repository: ghcr.io/berriai/litellm-non_root
              tag: main-v1.77.2-stable
            args:
              - --host
              - "::"
              - --port
              - "4000"
              - --config
              - /app/config.yaml
            env:
              TZ: America/New_York
              REDIS_HOST: redis://litellm-dragonfly:6379
              STORE_MODEL_IN_DB: True
              LITELLM_LOG: "DEBUG"
              LITELLM_MODE: "production"
              LITELLM_DONT_SHOW_FEEDBACK_BOX: "True"
              PROMETHEUS_URL: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
              QDRANT_API_BASE: http://qdrant:6333
            envFrom:
              - secretRef:
                  name: litellm-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/liveness # Change from "liveliness" to "liveness"
                    port: &port 4000
                  initialDelaySeconds: 30
                  periodSeconds: 60
                  timeoutSeconds: 10
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/readiness
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
    persistence:
      config:
        type: configMap
        name: litellm-configmap
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
            readOnly: true
          - path: /app/model_config.yaml
            subPath: model_config.yaml
            readOnly: true
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
            subPath: cache
          - path: /.npm
            subPath: npm
          - path: /tmp
            subPath: tmp
