apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: litellm-provider-config
spec:
  apiKeySecret: litellm-provider-secret
  apiKeySecretKey: LITELLM_API_KEY
  model: "xAI: Grok 4 Fast"
  provider: OpenAI
  openAI:
    baseUrl: "http://litellm.ai.svc.cluster.local:4000/v1"
