---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &app gha-rs-ac-ai-k8s-sandbox
spec:
  selector:
    matchLabels:
      helm.toolkit.fluxcd.io/name: *app
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
