---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app open-webui
  namespace: &namespace ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/dragonfly
    - ../../../../components/gatus/external
    - ../../../../components/volsync
  dependsOn:
    - name: dragonfly-operator
      namespace: database
    - name: postgres-cluster-17
      namespace: database
    - name: onepassword-store
      namespace: security
    - name: searxng
    - name: dragonfly-operator
      namespace: database
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
    # - apiVersion: postgres-operator.crunchydata.com/v1beta1
    #   kind: PostgresCluster
    #   failed: status.conditions.filter(e, e.type == 'ProxyAvailable').all(e, e.status == 'False')
    #   current: status.conditions.filter(e, e.type == 'ProxyAvailable').all(e, e.status == 'True')
  interval: 1h
  path: ./kubernetes/apps/ai/open-webui/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      GATUS_GROUP: *namespace
      GATUS_SUBDOMAIN: chat
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
