---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik
  namespace: &namespace security
spec:
  components:
    - ../../../../components/dragonfly
    - ../../../../components/gatus/external
  path: ./kubernetes/apps/security/authentik/app
  targetNamespace: *namespace
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  wait: false
  interval: 10m
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
  dependsOn:
    - name: postgres-cluster-17
      namespace: database
    - name: onepassword-store
      namespace: external-secrets
    - name: dragonfly-operator
      namespace: database
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      NAMESPACE: *namespace
      POSTGRES_DB: postgres-17-app
      GATUS_SUBDOMAIN: auth
