---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HOMEPAGE_VAR_TRUENAS_TOKEN: "{{ .TRUENAS_HOMEPAGE_WIDGET_API_KEY }}"
        HOMEPAGE_VAR_UNIFI_HOST_URL: "{{ .UNIFI_API_URL }}"
        HOMEPAGE_VAR_UNIFI_API_KEY: "{{ .UNIFI_API_KEY }}"
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_USERNAME }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_PASSWORD }}"

  dataFrom:
  - extract:
      key: unifi
  - extract:
      key: nas
  - extract:
      key: grafana
