---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../components/common
resources:
  # Flux-Kustomizations
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./lidarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./pvc/ks.yaml
  # - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./rreading-glasses/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
