---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
components:
  # @todo: Uncomment when Alerts are ready
  # - ../../components/flux/alerts
  - ../../components/common
resources:
  - ./alertmanager/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-state-metrics/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./prometheus-operator/ks.yaml
  - ./promtail/ks.yaml
  - ./gatus/ks.yaml
  - ./kromgo/ks.yaml
  - ./victoriametrics/ks.yaml
  - ./victorialogs/ks.yaml
  - ./vector/ks.yaml
