---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ceph-filesystem
