---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-music
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  storageClassName: ceph-filesystem
