---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-applications
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: cephfs
