---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tv
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: ceph-filesystem
