---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-system

components:
  - ../../components/common
  - ../../components/alerts

resources:
  - ./kagent/ks.yaml
  - ./kgateway/ks.yaml
