apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-db-app
  namespace: database
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: authentik-db-app
    template:
      engineVersion: v2
      data:
        username: "{{ .POSTGRES_DB_USER_NAME }}"
        password: "{{ .POSTGRES_DB_USER_PASSWORD }}"
        dbname: "{{ .POSTGRES_DB_NAME }}"
        host: "{{ .POSTGRES_DB_HOST }}.database.svc.cluster.local"
        port: "{{ .POSTGRES_DB_PORT }}"
        uri: "postgresql://{{ .POSTGRES_DB_USER_NAME }}:{{ .POSTGRES_DB_USER_PASSWORD }}@{{ .POSTGRES_DB_HOST }}.database.svc.cluster.local:{{ .POSTGRES_DB_PORT }}/{{ .POSTGRES_DB_NAME }}"
  data:
    - secretKey: POSTGRES_DB_USER_NAME
      remoteRef:
        key: authentik
        property: POSTGRES_DB_USER_NAME
    - secretKey: POSTGRES_DB_USER_PASSWORD
      remoteRef:
        key: authentik
        property: POSTGRES_DB_USER_PASSWORD
    - secretKey: POSTGRES_DB_NAME
      remoteRef:
        key: authentik
        property: POSTGRES_DB_NAME
    - secretKey: host
      remoteRef:
        key: authentik
        property: host
    - secretKey: port
      remoteRef:
        key: authentik
        property: port
    # Database Store
    - secretKey: POSTGRES_DB_HOST
      remoteRef:
        key: ${POSTGRES_DB:-postgres-16-app}
        property: host
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database-secrets
    - secretKey: POSTGRES_DB_PORT
      remoteRef:
        key: ${POSTGRES_DB:-postgres-16-app}
        property: port
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: database-secrets
