---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Security
    gethomepage.dev/name: Authentik
    gethomepage.dev/icon: authentik.png
    gethomepage.dev/pod-selector: app.kubernetes.io/name=authentik
    external-dns.alpha.kubernetes.io/target: "internal.sklab.dev"
spec:
  hostnames: ["auth.sklab.dev"]
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
    - name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: authentik-server
          namespace: security
          port: 80
