---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        annotations:
          secret.reloader.stakater.com/reload: &secret homepage-secret
          configmap.reloader.stakater.com/reload: &configmap homepage-config
        strategy: RollingUpdate
        serviceAccount:
          identifier: myServiceAccount
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.3.2
            env:
              TZ: ${CONFIG_TIMEZONE}
              # LOG_LEVEL: debug
            envFrom:
              - secretRef:
                  name: *secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: 3000
                    path: /api/healthcheck
                  initialDelaySeconds: 0
              readiness: *probes
              startup: *probes
    service:
      app:
        controller: main
        ports:
          http:
            port: 3000

    route:
      main:
        enabled: true
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        enabled: true
        type: configMap
        name: *configmap
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
    serviceAccount:
      myServiceAccount: {}
