---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  values:
    controllers:
      homepage:
        annotations:
          secret.reloader.stakater.com/reload: &secret homepage-secret
          configmap.reloader.stakater.com/reload: &configmap homepage-config
        strategy: RollingUpdate
        serviceAccount:
          identifier: myServiceAccount
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.5.0
            env:
              - name: HOMEPAGE_ALLOWED_HOSTS
                value: "*"
              - name: TZ
                value: ${CONFIG_TIMEZONE}
            ports:
              - name: http
                containerPort: 3000
                protocol: TCP
            envFrom:
              - secretRef:
                  name: *secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: 3000
                    path: /api/healthcheck
                  initialDelaySeconds: 0
              readiness: *probes
              startup: *probes
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000

    route:
      homepage:
        labels:
          app.kubernetes.io/name: *app
        annotations:
          gethomepage.dev/description: Dynamically Detected Homepage
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Cluster Management
          gethomepage.dev/icon: homepage.png
          gethomepage.dev/name: Homepage
        enabled: true
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                namespace: selfhosted
                port: 3000

    persistence:
      config:
        enabled: true
        type: configMap
        name: *configmap
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
    serviceAccount:
      myServiceAccount: {}
