---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
components:
  - ../../components/common
resources:
  # Pre Flux-Kustomizations
  # - ./namespace.yaml
  # Flux-Kustomizations
  - ./esphome/ks.yaml
  - ./home-assistant/ks.yaml
  - ./matter-server/ks.yaml
  - ./zigbee2mqtt/ks.yaml
