apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-pvc
  namespace: downloads
spec:
  accessModes: [ReadWriteMany]
  storageClassName: cephfs-media
  resources:
    requests:
      storage: 2Ti
