---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-block-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Ti
