---
storage:
  type: sqlite
  path: /config/sqlite.db
  caching: true

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

metrics: true

ui:
  title: Status | Gatus
  header: Status
  # logo: https://avatars.githubusercontent.com/u/213795
  link: https://github.com/Aviator-Coding
  buttons:
    - name: Github
      link: https://github.com/Aviator-Coding
    - name: Homelab
      link: https://github.com/Aviator-Coding/home-ops

web:
  port: ${WEB_PORT}
