---
storage:
  type: sqlite
  path: /config/sqlite.db
  caching: true

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: flux-webhook
    group: external
    url: https://flux-webhook.${SECRET_DOMAIN}/hook/healthz
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == any(200, 400, 404, 405)"

metrics: true

ui:
  title: Status | Gatus
  header: Status

web:
  port: ${WEB_PORT}
# debug: false
