---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperless-ngx-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Paperless-ngx app secrets
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"

        # PostgreSQL connection
        PAPERLESS_DBHOST: &dbhost "{{ .POSTGRES_DB_HOST }}"
        PAPERLESS_DBNAME: &dbname "{{ .POSTGRES_DB_NAME }}"
        PAPERLESS_DBUSER: &dbuser "{{ .POSTGRES_DB_USER_NAME }}"
        PAPERLESS_DBPASS: &dbpass "{{ .POSTGRES_DB_USER_PASSWORD }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: paperless-ngx
    - extract:
        key: cloudnative-pg
