---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name linkwarden-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"

        DATABASE_URL: "postgresql://{{ .POSTGRES_DB_USER_NAME }}:{{ .POSTGRES_DB_USER_PASSWORD }}@{{ .POSTGRES_DB_HOST }}:5432/{{ .POSTGRES_DB_NAME }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: &dbname "{{ .POSTGRES_DB_NAME }}"
        INIT_POSTGRES_HOST: &dbhost "{{ .POSTGRES_DB_HOST }}"
        INIT_POSTGRES_USER: &dbuser "{{ .POSTGRES_DB_USER_NAME }}"
        INIT_POSTGRES_PASS: &dbpass "{{ .POSTGRES_DB_USER_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: linkwarden
    - extract:
        key: cloudnative-pg
