---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${APP}-crunchy-postgres"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        ROOK_S3_ENDPOINT_INTERNAL: "{{ .ROOK_S3_ENDPOINT_INTERNAL }}"
        R2_S3_ENDPOINT: "{{ .R2_S3_ENDPOINT }}"
        MINIO_HOME_OPS_CRUNCHY_POSTGRES_ENDPOINT_URL: "{{ .MINIO_HOME_OPS_CRUNCHY_POSTGRES_ENDPOINT_URL }}"
        s3.conf: |
          [global]
          repo1-s3-key="{{ .ROOK_BUCKET_CRUNCHY_POSTGRES_ACCESS_KEY }}"
          repo1-s3-key-secret="{{ .ROOK_BUCKET_CRUNCHY_POSTGRES_SECRET_KEY }}"
          repo1-s3-endpoint="{{ .ROOK_S3_ENDPOINT_INTERNAL }}"
          repo2-s3-key="{{ .R2_K8S_ACCESS_KEY_ID }}"
          repo2-s3-key-secret="{{ .R2_K8S_SECRET_ACCESS_KEY }}"
          repo2-s3-endpoint="{{ .R2_S3_ENDPOINT }}"
          repo3-s3-key="{{ .MINIO_HOME_OPS_CRUNCHY_POSTGRES_ACCESS_KEY }}"
          repo3-s3-key-secret="{{ .MINIO_HOME_OPS_CRUNCHY_POSTGRES_SECRET_KEY }}"
          repo3-s3-endpoint="{{ .MINIO_HOME_OPS_CRUNCHY_POSTGRES_ENDPOINT_URL }}"
        encryption.conf: |
          [global]
          repo1-cipher-pass="{{ .ROOK_BUCKET_CRUNCHY_POSTGRES_REPOSITORY_CIPHER_PASS }}"
          repo2-cipher-pass="{{ .R2_K8S_CRUNCHY_POSTGRES_REPOSITORY_CIPHER_PASS }}"
          repo3-cipher-pass="{{ .MINIO_HOME_OPS_CRUNCHY_POSTGRES_REPOSITORY_CIPHER_PASS }}"

  dataFrom:
    - extract:
        key: cloudflare-r2
    - extract:
        key: nas
    - extract:
        key: rook-ceph
