---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${APP}-crunchy-postgres"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        s3.conf: |
          [global]
          ceph-s3-key="{{ .ceph-s3-key }}"
          ceph-s3-key-secret="{{ .ceph-s3-key-secret }}"
          ceph-s3-endpoint="{{ .ROOK_S3_ENDPOINT_INTERNAL }}"
          r2-s3-key="{{ .R2_ACCESS_KEY_ID }}"
          r2-s3-key-secret="{{ .R2_SECRET_ACCESS_KEY }}"
          r2-s3-endpoint="{{ .R2_S3_ENDPOINT }}"
          minio-s3-key="{{ .MINIO_HOME_OPS_CRUNCHY_POSTGRES_ACCESS_KEY }}"
          minio-s3-key-secret="{{ .MINIO_HOME_OPS_CRUNCHY_POSTGRES_SECRET_KEY }}"
          minio-s3-endpoint="{{ .MINIO_HOME_OPS_CRUNCHY_POSTGRES_ENDPOINT_URL }}"
        encryption.conf: |
          [global]
          ceph-cipher-pass="{{ .CEPH_CIPHER_PASS }}"
          r2-cipher-pass="{{ .R2_K8S_CRUNCHY_POSTGRES_REPOSITORY_CIPHER_PASS }}"
          minio-cipher-pass="{{ .MINIO_HOME_OPS_CRUNCHY_POSTGRES_REPOSITORY_CIPHER_PASS }}"

  dataFrom:
    - extract:
        key: cloudflare-r2
    - extract:
        key: nas
    - extract:
        key: rook-ceph
  data:
    - secretKey: ceph-s3-key
      remoteRef:
        key: crunchy-postgres-user
        property: AccessKey
    - secretKey: ceph-s3-key-secret
      remoteRef:
        key: crunchy-postgres-user
        property: SecretKey
