---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./arc-aviator-coding.yaml
  - ./arc-sklab-dev-runner.yaml
  - ./rbac.yaml
