---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./gateway-externalsecret.yaml
  - ./skills-externalsecret.yaml
  - ./rbac.yaml
  - ./instance.yaml
  - ./route.yaml
