apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: authentik-policy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal
      sectionName: https
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public
      sectionName: https
  traffic:
    extAuth:
      backendRef:
        name: ak-outpost-authentik-embedded-outpost
        namespace: security
        port: 9000
      http:
        path: |
          "/outpost.goauthentik.io/auth"
        allowedRequestHeaders:
          - Cookie
          - Authorization
        addRequestHeaders:
          x-forwarded-proto: request.scheme
          x-forwarded-host: request.host
          x-forwarded-uri: request.path
        allowedResponseHeaders:
          - Set-Cookie
          - X-authentik-username
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
