---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radarr-secret
    creationPolicy: Owner
    template:
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: &dbName "{{ .POSTGRES_DB_NAME }}"
        INIT_POSTGRES_HOST: &dbHost "{{ .POSTGRES_DB_HOST }}"
        INIT_POSTGRES_USER: &dbUser "{{ .POSTGRES_DB_USER_NAME }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .POSTGRES_DB_USER_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        RADARR__POSTGRES__HOST: *dbHost
        RADARR__POSTGRES__MAINDB: *dbName
        RADARR__POSTGRES__USER: *dbUser
        RADARR__POSTGRES__PASSWORD: *dbPass
        RADARR__POSTGRES__PORT: "5432"

        RADARR__AUTH__APIKEY: "{{ .RADARR_API_KEY }}"

  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: cloudnative-pg
