# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: &clusterName kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.10.10.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - &talosControlplaneVip 10.10.10.10
  - "talos.sklab.dev"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  #------------------------------------------------
  # # Talos 1
  #------------------------------------------------
  - &talos-k8s-mixed
    hostname: "talos-1"
    ipAddress: "10.10.10.11"
    installDisk: "/dev/disk/by-id/nvme-WD_BLACK_SN770M_1TB_251211800127"
    # Use factory image with custom kernel args and system extensions
    talosImageURL: factory.talos.dev/installer/05b4a47a70bc97786ed83d200567dcc8a13f731b164537ba59d5397d668851fa
    # installDiskSelector:
    #   # `/*` suffix is needed until
    #   # https://github.com/siderolabs/go-blockdevice/issues/114 is fixed
    #   busPath: /pci0000:00/0000:00:1d.3/0000:5a:00.0/nvme/* # M.2 slot Wifi Slot
    machineSpec:
      secureboot: false
    controlPlane: true
    networkInterfaces:
      # Explicitly tell Talos not to use the extra onboard NIC V-Pro
      - interface: enp89s0
        dhcp: false
        addresses: []
        routes: []
        # ignore: true

      - interface: bond0
        bond:
          interfaces:
            - enp2s0f0np0
            - enp2s0f1np1
          mode: 802.3ad
          # deviceSelectors:
          #   - permanentAddr: '58:47:ca:78:c8:9a'
          #   - permanentAddr: '58:47:ca:78:c8:9b'
          lacpRate: fast
          xmitHashPolicy: layer3+4
          miimon: 100
          updelay: 200
          downdelay: 200
        dhcp: true
        mtu: 9000
        # addresses:
        #   - 10.10.10.11/24
        vip:
          ip: *talosControlplaneVip
        # routes:
        #   - network: 0.0.0.0/0
        #     gateway: 10.10.10.1
      # - interface: lo
      #   routes:
      #     - network: 169.254.7.127/32
      #     - network: 169.254.116.108/32

  #------------------------------------------------
  # # Talos 2
  #------------------------------------------------
  - hostname: talos-2
    ipAddress: 10.10.10.12
    installDisk: "/dev/disk/by-id/nvme-WD_BLACK_SN770M_1TB_251211800809"
    # Use factory image with custom kernel args and system extensions
    talosImageURL: factory.talos.dev/installer/05b4a47a70bc97786ed83d200567dcc8a13f731b164537ba59d5397d668851fa
    # installDiskSelector:
    #   # `/*` suffix is needed until
    #   # https://github.com/siderolabs/go-blockdevice/issues/114 is fixed
    #   busPath: /pci0000:00/0000:00:1d.3/0000:5a:00.0/nvme/* # M.2 slot Wifi Slot
    machineSpec:
      secureboot: false
    controlPlane: true
    networkInterfaces:
      # Explicitly tell Talos not to use the extra onboard NIC V-Pro
      - interface: enp89s0
        dhcp: false
        addresses: []
        routes: []
        # ignore: true

      - interface: bond0
        bond:
          interfaces:
            - enp2s0f0np0
            - enp2s0f1np1
          mode: 802.3ad
          lacpRate: fast
          xmitHashPolicy: layer3+4
          miimon: 100
          updelay: 200
          downdelay: 200
        dhcp: true
        mtu: 9000
        # addresses:
        #   - 10.10.10.12/24
        vip:
          ip: *talosControlplaneVip
        # routes:
        #   - network: 0.0.0.0/0
        #     gateway: 10.10.10.1

      # - interface: lo
      #   routes:
      #     - network: 169.254.7.127/32
      #     - network: 169.254.116.108/32

  #------------------------------------------------
  # # Talos 3
  #------------------------------------------------
  - hostname: talos-3
    ipAddress: 10.10.10.13
    installDisk: "/dev/disk/by-id/nvme-WD_BLACK_SN770M_1TB_251211800007"
    # Use factory image with custom kernel args and system extensions
    talosImageURL: factory.talos.dev/installer/05b4a47a70bc97786ed83d200567dcc8a13f731b164537ba59d5397d668851fa
    # installDiskSelector:
    #   # `/*` suffix is needed until
    #   # https://github.com/siderolabs/go-blockdevice/issues/114 is fixed
    #   busPath: /pci0000:00/0000:00:1d.3/0000:5a:00.0/nvme/* # M.2 slot Wifi Slot
    machineSpec:
      secureboot: false
    controlPlane: true
    networkInterfaces:
      # Explicitly tell Talos not to use the extra onboard NIC V-Pro
      - interface: enp89s0
        dhcp: false
        addresses: []
        routes: []
        # ignore: true

      - interface: bond0
        bond:
          interfaces:
            - enp2s0f0np0
            - enp2s0f1np1
          mode: 802.3ad
          lacpRate: fast
          xmitHashPolicy: layer3+4
          miimon: 100
          updelay: 200
          downdelay: 200
        dhcp: true
        mtu: 9000
        # addresses:
        #   - 10.10.10.13/24
        vip:
          ip: *talosControlplaneVip
      #     - network: 0.0.0.0/0
      #       gateway: 10.10.10.1

      # - interface: lo
      #   routes:
      #     - network: 169.254.7.127/32
      #     - network: 169.254.116.108/32

# Global patches
patches:
  # All kernel args are now in the factory image (schematic.yaml)
  # No need to remove extraKernelArgs as they don't exist in machine config
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-udev.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-features.yaml"
  # - "@./patches/global/user-volume-config.yaml"

# Controller patches
controlPlane:
  nodeLabels:
    topology.kubernetes.io/region: *clusterName
    intel.feature.node.kubernetes.io/gpu: "true"
    topology.kubernetes.io/zone: m

  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"
