---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./alerts
  - ./prometheusrules
  - ./scrapeconfigs
patches:
  - target:
      kind: StatefulSet
      name: prometheus-kube-prometheus-stack
      namespace: monitoring
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/metadata/name
        value: storage-prometheus-db
      - op: replace
        path: /metadata/name
        value: prometheus
