---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: volsync
  namespace: system
spec:
  store: ceph-objectstore
  clusterNamespace: rook-ceph
  displayName: volsync-user
  quotas:
    maxBuckets: 10000
    maxSize: 20G
    maxObjects: 100000
  capabilities:
    user: "*"
    bucket: "*"
