---
apiVersion: v1
kind: ConfigMap
metadata:
  name: obsidian-livesync-config
data:
  local.ini: |
    [chttpd]
    bind_address = 0.0.0.0
    port = 5984
    max_http_request_size = 4294967296

    [httpd]
    enable_cors = true
    WWW-Authenticate = Basic realm="couchdb"

    [cors]
    origins = app://obsidian.md,capacitor://localhost,http://localhost
    credentials = true
    headers = accept, authorization, content-type, origin, referer
    methods = GET, PUT, POST, HEAD, DELETE
    max_age = 3600

    [couchdb]
    single_node = true
    max_document_size = 50000000

    [chttpd_auth]
    require_valid_user = true

    [compactions]
    _default = [{db_fragmentation, "70%"}, {view_fragmentation, "60%"}]
