---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-claw-skills-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: my-claw-skills-secret
    template:
      data:
        TAVILY_API_KEY: "{{ .TAVILY_API_KEY }}"
        GEMINI_API_KEY: "{{ .GEMINI_API_KEY }}"
        NOTION_API_KEY: "{{ .NOTION_API_KEY }}"
        BF_API_KEY: "{{ .BF_API_KEY }}"
        GOOGLE_CLIENT_SECRET: "{{ .CLAWBOT_GOOGLE }}"
        client_secret.json: "{{ .CLAWBOT_GOOGLE }}"
        GH_TOKEN: "{{ .HOMEOPS_CLAW_PAT }}"
  dataFrom:
    - extract:
        key: openclaw-skills
    - extract:
        key: travily
    - extract:
        key: ai-keys
    - extract:
        key: notion
    - extract:
        key: banana_farmer
    - extract:
        key: google
    - extract:
        key: github
