---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-16-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: postgres-16
        group: Database
        url: tcp://postgres-16-rw.database.svc.cluster.local:5432
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
