---
apiVersion: v1
kind: Service
metadata:
  name: postgres-16-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "postgres-16.${SECRET_DOMAIN}"
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-16
    cnpg.io/instanceRole: primary
