---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP}-dragonfly-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Redis (${APP})
        group: Services
        url: tcp://${APP}-dragonfly.${NAMESPACE:=database}.svc.cluster.local:6379
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
            send-on-resolved: true
