---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system

components:
  - ../../components/common
  - ../../components/alerts

resources:
  - ./fstrim/ks.yaml
  - ./generic-device-plugin/ks.yaml
  - ./intel-device-plugin-operator/ks.yaml
  - ./volsync/ks.yaml
  - ./openebs-hostpath/ks.yaml
