---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vector-agent-gateway
  namespace: monitoring
spec:
  gatewayClassName: cilium
  listeners:
    - name: mikrotik
      port: 1514
      protocol: UDP
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: vector-agent-mikrotik
  namespace: monitoring
spec:
  parentRefs:
    - name: vector-agent-gateway
      namespace: monitoring
      sectionName: mikrotik
  rules:
    - backendRefs:
        - name: vector-agent
          port: 1514
