---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${job}
  namespace: default
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      nodeName: ${node}
      hostPID: true
      hostNetwork: true
      containers:
        - name: main
          image: docker.io/library/alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - apk add --no-cache sgdisk util-linux util-linux-misc parted device-mapper;
              sgdisk --zap-all /host${disk};
              dd if=/dev/zero of=/host${disk} bs=1M count=100 oflag=direct;
              blkdiscard /host${disk};
              partprobe /host${disk};
          securityContext:
            privileged: true
          resources: {}
          volumeMounts:
            - name: host-dev
              mountPath: /host/dev
              mountPropagation: Bidirectional
            - name: host-usr-bin
              mountPath: /host/usr/bin
              readOnly: true
          env:
            - name: PATH
              value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/host/usr/bin"
      volumes:
        - name: host-dev
          hostPath:
            path: /dev
            type: Directory
        - name: host-usr-bin
          hostPath:
            path: /usr/bin
            type: Directory
