---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-gateway-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: openclaw-gateway-token
    template:
      data:
        token: "{{ .OPENCLAW_GATEWAY_TOKEN }}"
  dataFrom:
    - extract:
        key: openclaw
