---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  NAMESPACE: actions-runner-system
  REPO: aviator-coding/home-ops

tasks:

  diagnose:
    desc: Show current status of runners, listeners, and controller
    cmds:
      - |
        echo "=== Controller Pods ==="
        kubectl get pods -n {{.NAMESPACE}} -l app.kubernetes.io/name=gha-runner-scale-set-controller -o wide
        echo ""
        echo "=== Listener Pods ==="
        kubectl get pods -n {{.NAMESPACE}} -l app.kubernetes.io/component=listener -o wide
        echo ""
        echo "=== Runner Pods ==="
        kubectl get pods -n {{.NAMESPACE}} -l actions.github.com/scale-set-name -o wide
        echo ""
        echo "=== HelmRelease Status ==="
        flux get hr -n {{.NAMESPACE}}
        echo ""
        echo "=== Recent Events ==="
        kubectl get events -n {{.NAMESPACE}} --sort-by='.metadata.creationTimestamp' | tail -20
        echo ""
        echo "=== GitHub Registered Runners ==="
        gh api repos/{{.REPO}}/actions/runners --jq '.runners[] | "\(.id) | \(.name) | \(.status) | busy=\(.busy)"' || echo "Failed to query GitHub API"
        echo ""
        echo "=== CronJob Status ==="
        kubectl get cronjob -n {{.NAMESPACE}}
        echo ""
        echo "=== Recent Maintenance Jobs ==="
        kubectl get jobs -n {{.NAMESPACE}} -l batch.kubernetes.io/job-name --sort-by='.metadata.creationTimestamp' | tail -5

  restart-listener:
    desc: Delete listener pod to force reconnection to GitHub
    cmds:
      - kubectl delete pods -n {{.NAMESPACE}} -l app.kubernetes.io/component=listener
      - echo "Listener pod deleted. Waiting for restart..."
      - kubectl wait --for=condition=ready pod -n {{.NAMESPACE}} -l app.kubernetes.io/component=listener --timeout=120s
      - echo "Listener pod is ready"

  cleanup-stale-runners:
    desc: Manually trigger cleanup of stale/offline runners from GitHub API
    cmds:
      - |
        echo "Fetching runners from GitHub..."
        RUNNERS=$(gh api repos/{{.REPO}}/actions/runners --jq '.runners[] | select(.status == "offline" and .busy == false) | .id')
        if [ -z "$RUNNERS" ]; then
          echo "No stale runners found"
        else
          echo "Found stale runners, deleting..."
          for id in $RUNNERS; do
            echo "Deleting runner $id..."
            gh api -X DELETE "repos/{{.REPO}}/actions/runners/$id" && echo "Deleted $id" || echo "Failed to delete $id"
          done
        fi

  cancel-stuck-runs:
    desc: Cancel workflow runs stuck in queued state for more than 30 minutes
    vars:
      STUCK_MINUTES: '{{.STUCK_MINUTES | default "30"}}'
    cmds:
      - |
        echo "Checking for workflow runs stuck in queued state for more than {{.STUCK_MINUTES}} minutes..."
        CURRENT_TIME=$(date +%s)
        THRESHOLD=$(({{.STUCK_MINUTES}} * 60))

        gh run list --repo {{.REPO}} --status queued --json databaseId,createdAt,name --limit 100 | \
        jq -r --argjson threshold "$THRESHOLD" --argjson now "$CURRENT_TIME" \
          '.[] | select(($now - ((.createdAt | gsub("[TZ]"; " ") | strptime("%Y-%m-%d %H:%M:%S") | mktime))) > $threshold) | "\(.databaseId) \(.name)"' | \
        while read -r id name; do
          if [ -n "$id" ]; then
            echo "Cancelling stuck run: $name (id=$id)"
            gh run cancel "$id" --repo {{.REPO}} && echo "Cancelled $id" || echo "Failed to cancel $id"
          fi
        done
        echo "Done checking stuck runs"

  reset-scale-set:
    desc: Full recreation of AutoscalingRunnerSet (use when runners are completely stuck)
    cmds:
      - echo "WARNING - This will delete and recreate the runner scale set"
      - echo "All active jobs will be interrupted!"
      - echo ""
      - echo "Suspending HelmReleases..."
      - flux suspend hr -n {{.NAMESPACE}} gha-runner-scale-set-aviator-coding-home-ops
      - kubectl delete hr -n {{.NAMESPACE}} gha-runner-scale-set-aviator-coding-home-ops --wait=true
      - echo "Waiting for cleanup..."
      - sleep 10
      - echo "Resuming HelmReleases..."
      - flux resume hr -n {{.NAMESPACE}} gha-runner-scale-set-aviator-coding-home-ops
      - echo "Waiting for reconciliation..."
      - flux reconcile ks -n flux-system actions-runner-gha-runner-scale-set-aviator-coding-home-ops --with-source
      - echo "Waiting for listener to be ready..."
      - sleep 10
      - kubectl wait --for=condition=ready pod -n {{.NAMESPACE}} -l app.kubernetes.io/component=listener --timeout=180s
      - echo "Runner scale set has been reset"
    prompt: This will interrupt all active jobs. Are you sure?

  run-maintenance:
    desc: Manually trigger the maintenance CronJob
    cmds:
      - |
        JOB_NAME="runner-maintenance-manual-$(date +%s)"
        echo "Creating manual maintenance job: $JOB_NAME"
        kubectl create job -n {{.NAMESPACE}} "$JOB_NAME" --from=cronjob/runner-maintenance
        echo "Waiting for job to complete..."
        kubectl wait --for=condition=complete job/"$JOB_NAME" -n {{.NAMESPACE}} --timeout=300s || true
        echo ""
        echo "=== Job Logs ==="
        kubectl logs -n {{.NAMESPACE}} "job/$JOB_NAME"

  logs-controller:
    desc: View controller logs
    cmds:
      - kubectl logs -n {{.NAMESPACE}} -l app.kubernetes.io/name=gha-runner-scale-set-controller --tail=100 -f

  logs-listener:
    desc: View listener logs
    cmds:
      - kubectl logs -n {{.NAMESPACE}} -l app.kubernetes.io/component=listener --tail=100 -f

  logs-maintenance:
    desc: View most recent maintenance job logs
    cmds:
      - |
        LATEST_JOB=$(kubectl get jobs -n {{.NAMESPACE}} --sort-by='.metadata.creationTimestamp' -o name | grep runner-maintenance | tail -1)
        if [ -n "$LATEST_JOB" ]; then
          echo "Logs for $LATEST_JOB:"
          kubectl logs -n {{.NAMESPACE}} "$LATEST_JOB"
        else
          echo "No maintenance jobs found"
        fi
