---
# Template PV for shared media storage - points to the same CephFS subvolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-media-${NAMESPACE:-default}-pv
  labels:
    storage.kubernetes.io/csiProvisionerIdentity: rook-ceph.cephfs.csi.ceph.com
    shared-media.io/component: "true"
spec:
  capacity:
    storage: ${SHARED_MEDIA_CAPACITY:-5Ti}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # Empty for static binding
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: ceph-filesystem
      subvolumeGroup: media
    # Points to the shared media subvolume - all namespaces access the same storage
    volumeHandle: ${SHARED_MEDIA_VOLUME_HANDLE:-0001-0009-rook-ceph-0000000000000001-6d1c35aa-5b29-43a0-9f8a-d2c11363423b}
