---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name n8n-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_SECRET_KEY }}"

        DB_TYPE: postgresdb
        DB_POSTGRESDB_DATABASE: &dbname "{{ .POSTGRES_DB_NAME }}"
        DB_POSTGRESDB_HOST: &dbhost "{{ .POSTGRES_DB_HOST }}"
        DB_POSTGRESDB_USER: &dbuser "{{ .POSTGRES_DB_USER_NAME }}"
        DB_POSTGRESDB_PASSWORD: &dbpass "{{ .POSTGRES_DB_USER_PASSWORD }}"
        DB_POSTGRESDB_PORT: "5432"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: n8n
    - extract:
        key: cloudnative-pg
