---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name readarr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        READARR__API_KEY: "{{ .READARR__API_KEY }}"
        READARR__POSTGRES_HOST: &dbHost "{{ .POSTGRES_DB_HOST }}"
        READARR__POSTGRES_PORT: "5432"
        READARR__POSTGRES_USER: &dbUser "{{ .POSTGRES_DB_USER_NAME }}"
        READARR__POSTGRES_PASSWORD: &dbPass "{{ .POSTGRES_DB_USER_PASSWORD }}"
        READARR__POSTGRES_MAIN_DB: &main "{{ .POSTGRES_DB_NAME }}_main"
        READARR__POSTGRES_LOG_DB: &log "{{ .POSTGRES_DB_NAME }}_log"
        READARR__POSTGRES_CACHE_DB: &cache "{{ .POSTGRES_DB_NAME }}_cache"
        # Postgres Init
        INIT_POSTGRES_DBNAME: readarr_main readarr_log readarr_cache
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: readarr
    - extract:
        key: cloudnative-pg
