---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name lidarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lidarr-secret
    template:
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: &dbName "{{ .POSTGRES_DB_NAME }}"
        INIT_POSTGRES_HOST: &dbHost "{{ .POSTGRES_DB_HOST }}"
        INIT_POSTGRES_USER: &dbUser "{{ .POSTGRES_DB_USER_NAME }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .POSTGRES_DB_USER_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

        LIDARR__POSTGRES__HOST: *dbHost
        LIDARR__POSTGRES__MAINDB: *dbName
        LIDARR__POSTGRES__USER: *dbUser
        LIDARR__POSTGRES__PASSWORD: *dbPass
        LIDARR__POSTGRES__PORT: "5432"

        LIDARR__AUTH__APIKEY: "{{ .LIDARR_API_KEY }}"

  dataFrom:
    - extract:
        key: lidarr
    - extract:
        key: cloudnative-pg
