apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:tw9SwqZA+oXf,iv:OSSM9cE2+dmA0kpkBiBPyTCx3tMtvM8IHDxQ/nhGYJY=,tag:GGtAHO3SxV87hBNPWS0RUA==,type:str]
sops:
  age:
    - recipient: age13qrheg54vtg3azk0qa7ua7fnszvcc839ln8zazpdvszsfxekrf3s8jytnl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNGhVTTBRTjFmeU8xWkVk
        WHRzcGVyRjZldzVHc01kSkQvZi9sRFFSWWxRCmhVODZ2RzZ3N0dTb3oxN1BxeDVr
        akFFekhKMlNuNVRnZ3BCZkY1dHhOY2sKLS0tIHppSVNuNW56VldkQVJYM3QxRmdU
        TnA2Q3B5T3JjK0EyUGJCdjJaU0NOcncKTCfDyE6M4kHNKyeekI2zqnShnv2zE6kD
        JEWCxKSxgYnHZKcm8dsKMM19RbpzgiTB6sfH2ICWbf7eZMIAvfkAqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-11T01:35:59Z"
  mac: ENC[AES256_GCM,data:c+52r0YxP0U3iXHXaVM6jySlyS5ray59URcb2kG/SC/Zgrj3jcq/66uEZK9txXH5/RmIuj8gURk9AMNB7YAr2yB16km5fD3jBglfQl8VfIrTqXFKj9nfsltlkovYH8OU8848KGD0O99qQxcZX3WMzhrZGd4DkBOldvRiamKCFYc=,iv:3J59eKhe64Fdq/7S6P+bJdaxUiuCgIaz5WEKac2uKtE=,tag:cUwZY0ieHSaiKvgfn2nr9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
