---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: se-gateway
  annotations:
    io.cilium/lb-ipam-ips: "10.50.0.120" # force this VIP
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 10.50.0.120
  listeners:
    - name: se-udp
      protocol: UDP
      port: 27016
    - name: se-tcp
      protocol: TCP
      port: 27016
    - name: se-http
      protocol: HTTP
      port: 8081
---
apiVersion: gateway.networking.k8s.io/v1
kind: UDPRoute
metadata:
  name: se-udp-27016
  namespace: gaming
spec:
  parentRefs:
    - name: se-gateway
      sectionName: se-udp
  rules:
    - backendRefs:
        - name: space-engineers-ds # your Service name
          port: 27016
        - name: steam-udp
          port: 8766
        - name: steam2-udp
          port: 27015
---
apiVersion: gateway.networking.k8s.io/v1
kind: TCPRoute
metadata:
  name: se-tcp-27016
  namespace: gaming
spec:
  parentRefs:
    - name: se-gateway
      sectionName: se-tcp
  rules:
    - backendRefs:
        - name: space-engineers-ds
          port: 27016
