---
# PVC for Space Engineers instances data (RWO for snapshots)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: space-engineers-ds
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 50Gi
---
# PVC for Space Engineers plugins (RWX for shared access)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: space-engineers-ds-plugins
  namespace: gaming
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 10Gi
