---
apiVersion: v1
kind: Service
metadata:
  name: postgres-17-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "postgres-17.${SECRET_DOMAIN}"
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-17
    cnpg.io/instanceRole: primary
