---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname rreading-glasses
  namespace: &namespace downloads
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: onepassword-store
      namespace: security
    - name: volsync
      namespace: system
    - name: postgres-cluster-17
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/downloads/rreading-glasses/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
