---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ceph-bucket-coder-postgres
spec:
  generateBucketName: coder-postgres
  storageClassName: ceph-bucket
---
#################################################################################################################
# Create an object store user for access to the s3 endpoint.
#################################################################################################################
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: coder-user
  namespace: rook-ceph # namespace:cluster
spec:
  store: ceph-objectstore
  displayName: "Coder Postgres S3 User"
