---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name coder
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        # SMTP Credentials
        CODER_EMAIL_AUTH_PASSWORD: "{{ .SMTP_PASSWORD }}"
        CODER_EMAIL_AUTH_USERNAME: "{{ .SMTP_USERNAME }}"
        CODER_EMAIL_SMARTHOST: "{{ .SMTP_HOST }}:{{ .SMTP_PORT }}"
        CODER_EMAIL_SMARTHOST_TLS: "{{ .SMTP_SSL }}"
        # Coder OIDC
        CODER_OIDC_CLIENT_ID: "{{ .CODER_OAUTH_CLIENT_ID }}"
        CODER_OIDC_CLIENT_SECRET: "{{ .CODER_OAUTH_CLIENT_SECRET }}"
        CODER_OIDC_ALLOWED_GROUPS: "{{ .CODER_OAUTH_ALLOWED_GROUPS }}"
        CODER_OIDC_EMAIL_DOMAIN: "{{ .CODER_OAUTH_EMAIL_DOMAIN }}"

        # Postgress Settings
        INIT_POSTGRES_HOST: "{{ .POSTGRES_DB_HOST }}"
        INIT_POSTGRES_DBNAME: "{{ .POSTGRES_DB_NAME }}"
        INIT_POSTGRES_USER: "{{ .POSTGRES_DB_USER_NAME }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_DB_USER_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_DB_USER_PASSWORD }}"
        CODER_PG_CONNECTION_URL: "postgres://{{.POSTGRES_DB_USER_NAME}}:{{.POSTGRES_DB_USER_PASSWORD}}@{{.POSTGRES_DB_HOST}}:5432/{{.POSTGRES_DB_NAME}}?sslmode=disable"

  dataFrom:
    - extract:
        key: smtp-bravo
    - extract:
        key: coder
    - extract:
        key: cloudnative-pg
