---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name coder
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        # SMTP Credentials
        CODER_EMAIL_AUTH_PASSWORD: "{{ .SMTP_HOST }}"
        CODER_EMAIL_AUTH_USERNAME: "{{ .SMTP_USERNAME }}"
        CODER_EMAIL_SMARTHOST: "{{ .SMTP_HOST }}:{{ .SMTP_PORT }}"
        CODER_EMAIL_SMARTHOST_TLS: "{{ .SMTP_SSL }}"
        # Coder OIDC
        # CODER_OIDC_ALLOWED_GROUPS: "{{ .coder_oidc_allowed_groups }}"
        # CODER_OIDC_CLIENT_ID: "{{ .coder_oidc_client_id }}"
        # CODER_OIDC_CLIENT_SECRET: "{{ .coder_oidc_client_secret }}"
        # CODER_OIDC_EMAIL_DOMAIN: "{{ .coder_oidc_email_domain }},gmail.com"
        # Coder Postgres
        # INIT_POSTGRES_HOST: "{{ .postgres_host }}"
        # INIT_POSTGRES_DBNAME: "{{ .coder_postgres_dbname }}"
        # INIT_POSTGRES_USER: "{{ .coder_postgres_user }}"
        # INIT_POSTGRES_PASS: "{{ .coder_postgres_password }}"
        # INIT_POSTGRES_SUPER_PASS: "{{ .postgres_super_password }}"
        # CODER_PG_CONNECTION_URL: "postgres://{{.coder_postgres_user}}:{{.coder_postgres_password}}@{{.postgres_host}}:5432/{{.coder_postgres_dbname}}?sslmode=disable"

  dataFrom:
    # - extract:
    #     key: coder
    - extract:
        key: smtp-bravo
    # - extract:
    #     key: cloudnative-pg
