---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-minio"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-volsync-minio-secret"
    template:
      data:
        RESTIC_REPOSITORY: "s3:http://nas.${SECRET_DOMAIN}:9000/{{ .MINIO_VOLSYNC_RESTIC_REPOSITORY }}/${APP}"
        RESTIC_PASSWORD: "{{ .MINIO_VOLSYNC_RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .MINIO_HOME_OPS_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .MINIO_HOME_OPS_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: volsync-template
