---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}-minio"
spec:
  sourcePVC: "${APP}"
  trigger:
    schedule: "0 */3 * * *"  # Every 3 hours - regular NAS backups
  restic:
    pruneIntervalDays: 14
    repository: "${APP}-volsync-minio-secret"
    copyMethod: "${VOLSYNC_COPYMETHOD:-Snapshot}"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:-csi-ceph-blockpool}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:-ceph-block}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:-ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:-2Gi}"
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:-1000}
      runAsGroup: ${VOLSYNC_PGID:-1000}
      fsGroup: ${VOLSYNC_PGID:-1000}
    retain:
      daily: 14    # Keep 14 daily snapshots (2 weeks)
      weekly: 8    # Keep 8 weekly snapshots (2 months)
      monthly: 6   # Keep 6 monthly snapshots
