---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        # Open-WebUI Config
        ADMIN_EMAIL: "{{ .ADMIN_EMAIL }}"
        ENABLE_ADMIN_CHAT_ACCESS: "true"
        ENABLE_ADMIN_EXPORT: "true"
        DEFAULT_USER_ROLE: "user"
        WEBUI_SECRET_KEY: "{{ .WEBUI_SECRET_KEY }}"
        # OAUTH
        ENABLE_LOGIN_FORM: "false"
        ENABLE_OAUTH_SIGNUP: "true"
        OAUTH_MERGE_ACCOUNTS_BY_EMAIL: "true"
        OAUTH_PROVIDER_NAME: Authentik
        OPENID_PROVIDER_URL: https://auth.${SECRET_DOMAIN}/application/o/open-webui/.well-known/openid-configuration
        OAUTH_SCOPES: openid email profile
        OPENID_REDIRECT_URI: https://chat.{SECRET_DOMAIN}/oauth/oidc/callback
        OAUTH_CLIENT_ID: "{{ .OPEN_WEBUI_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OPEN_WEBUI_CLIENT_SECRET }}"
        # OPENAI
        # ENABLE_OPENAI_API: "true"
        # OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        # QDRANT
        VECTOR_DB: qdrant
        QDRANT_URI: http://qdrant:6333
        QDRANT_API_KEY: "{{ .QDRANT_API_KEY }}"

        # PostgreSQL Connection URL
        DATABASE_URL: "postgresql://{{ .POSTGRES_DB_USER_NAME }}:{{ .POSTGRES_DB_USER_PASSWORD }}@{{ .POSTGRES_DB_HOST }}:5432/{{ .POSTGRES_DB_NAME }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .POSTGRES_DB_NAME }}"
        INIT_POSTGRES_HOST: "{{ .POSTGRES_DB_HOST }}"
        INIT_POSTGRES_USER: "{{ .POSTGRES_DB_USER_NAME }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_DB_USER_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: open-webui
    - extract:
        key: qdrant
    - extract:
        key: cloudnative-pg
