---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app coder
  namespace: &namespace coder
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../components/gatus/guarded
  dependsOn:
    - name: postgres-cluster-17
      namespace: database
    - name: onepassword-store
      namespace: security
    - name: rook-ceph
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/coder/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: coder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: true
